import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { parse as parseYaml } from "yaml";
import {
  banyanProfiles,
  generateBanyanYaml,
  generateOpencodeJsonc,
  listAgents,
  syncDerivedConfigs,
} from "./sync.js";
import type { ResolvedConfig } from "./types.js";

const registry = {
  default: "codex",
  codingAgents: {
    default: "codex",
    agents: {
      zsh: { label: "zsh", tags: ["banyan"], command: "" },
      codex: {
        label: "Codex",
        provider: "codex",
        weight: 2,
        tags: ["banyan", "coding"],
        command: "codex -p terra --dangerously-bypass-approvals-and-sandbox",
        banyanCommand: "codex",
      },
      hy3: {
        label: "Hunyuan",
        provider: "hunyuan",
        tags: ["banyan"],
        command: "opencode --agent hy3",
        aliases: ["hy"],
        opencodeName: "hy3",
        opencode: { mode: "primary", model: "opencode-go/hy3" },
      },
      ghost: {
        label: "Ghost",
        command: "ghost",
      },
      vision: {
        provider: "minimax",
        picker: false,
        opencodeName: "vision",
        opencode: { mode: "primary", model: "opencode-go/minimax-m3" },
      },
      build: {
        picker: false,
        opencode: { disable: true },
      },
    },
    opencode: {
      default_agent: "0xAlpha",
      permission: { "*": "allow" },
    },
  },
};

function resolvedWith(home: string): ResolvedConfig {
  return {
    config: registry,
    root: home,
    configFiles: [],
    aliasIndex: {},
  };
}

test("banyan profiles include picker entries in registry order and skip opencode-only ones", () => {
  const profiles = banyanProfiles({ config: registry, root: "", configFiles: [], aliasIndex: {} });
  assert.deepEqual(profiles.map((profile) => profile.id), ["zsh", "codex", "hy3"]);
  assert.equal(profiles[1]!.command, "codex");
});

test("generated banyan yaml round-trips through a YAML parser with quoted scalars", () => {
  const yaml = generateBanyanYaml({ config: registry, root: "", configFiles: [], aliasIndex: {} });
  assert.match(yaml, /^# Generated by `workit sync`/);
  const parsed = parseYaml(yaml) as {
    session_launches: Array<Record<string, string>>;
  };
  assert.deepEqual(
    parsed.session_launches.map((profile) => profile.id),
    ["zsh", "codex", "hy3"],
  );
  const hunyuan = parsed.session_launches[2]!;
  assert.equal(hunyuan.label, "Hunyuan");
  assert.equal(hunyuan.command, "opencode --agent hy3");
  assert.equal(parsed.session_launches[0]!.command, "");
});

test("opencode jsonc keeps schema first, passthrough settings, and generated agent map", () => {
  const jsonc = generateOpencodeJsonc({ config: registry, root: "", configFiles: [], aliasIndex: {} });
  const doc = JSON.parse(jsonc) as Record<string, unknown>;
  assert.deepEqual(Object.keys(doc), ["$schema", "default_agent", "permission", "agent"]);
  const agent = doc.agent as Record<string, unknown>;
  assert.deepEqual(Object.keys(agent), ["build", "hy3", "vision"]);
  assert.deepEqual(agent.build, { disable: true });
  assert.deepEqual(agent.hy3, { mode: "primary", model: "opencode-go/hy3" });
});

test("syncDerivedConfigs writes both targets once, backs up originals, then reports no changes", () => {
  const home = mkdtempSync(join(tmpdir(), "workit-sync-"));
  const banyanPath = join(home, ".banyan", "config.yml");
  const opencodePath = join(home, ".config", "opencode", "opencode.jsonc");
  mkdirSync(dirname(banyanPath), { recursive: true });
  mkdirSync(dirname(opencodePath), { recursive: true });
  writeFileSync(banyanPath, "session_launches:\n  - id: zsh\n    label: zsh\n    command: \"\"\n");
  writeFileSync(opencodePath, '{\n  "$schema": "https://opencode.ai/config.json"\n}\n');

  const options = {
    homeDirectory: home,
  };
  const envKeys = ["WORKIT_BANYAN_CONFIG", "WORKIT_OPENCODE_CONFIG"] as const;
  const saved = envKeys.map((key) => process.env[key]);
  for (const key of envKeys) delete process.env[key];

  try {
    const resolved = resolvedWith(home);
    const first = syncDerivedConfigs(resolved, { ...options });
    assert.equal(first.changed, true);
    assert.equal(first.targets.length, 2);
    assert.ok(first.targets.every((target) => target.changed));
    assert.ok(existsSync(`${banyanPath}.orig`));
    assert.ok(existsSync(`${opencodePath}.orig`));

    const second = syncDerivedConfigs(resolved, { ...options });
    assert.equal(second.changed, false);

    const checkOnly = syncDerivedConfigs(resolved, { ...options, check: true });
    assert.equal(checkOnly.changed, false);
    assert.equal(readFileSync(banyanPath, "utf8"), generateBanyanYaml(resolved));
    assert.equal(readFileSync(opencodePath, "utf8"), generateOpencodeJsonc(resolved));
  } finally {
    envKeys.forEach((key, index) => {
      if (saved[index] !== undefined) process.env[key] = saved[index]!;
    });
  }
});

test("syncDerivedConfigs refuses to run without a registry", () => {
  assert.throws(
    () =>
      syncDerivedConfigs(
        { config: {}, root: "", configFiles: [], aliasIndex: {} },
        { homeDirectory: mkdtempSync(join(tmpdir(), "workit-noreg-")) },
      ),
    /coding-agent registry/,
  );
});

test("listAgents returns launchable entries, optionally filtered by tag", () => {
  const resolved = { config: registry, root: "", configFiles: [], aliasIndex: {} };
  assert.deepEqual(
    listAgents(resolved).map((entry) => entry.name),
    ["codex", "hy3", "ghost"],
  );
  const review = listAgents(resolved, "review");
  assert.deepEqual(review, []);
  listAgents(resolved, "banyan").forEach((entry) => {
    assert.notEqual(entry.command, "");
  });
  assert.deepEqual(listAgents(resolved, "coding").map((entry) => entry.name), ["codex"]);
});
