import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { AGENTS_FILE, resolveHomePath } from "./config.js";
import type { CodingAgentEntry, ResolvedConfig } from "./types.js";

export const OPENCODE_SCHEMA = "https://opencode.ai/config.json";

export interface SyncTargetResult {
  path: string;
  changed: boolean;
  backupPath?: string;
}

export interface SyncResult {
  targets: SyncTargetResult[];
  /** True when any derived file had to be rewritten. */
  changed: boolean;
}

export interface SyncOptions {
  /** Compare only: report stale targets without writing. */
  check?: boolean;
  homeDirectory?: string;
}

function banyanConfigPath(home?: string): string {
  return process.env.WORKIT_BANYAN_CONFIG ?? join(home ?? homedir(), ".banyan", "config.yml");
}

function opencodeConfigPath(home?: string): string {
  return (
    process.env.WORKIT_OPENCODE_CONFIG ??
    join(home ?? homedir(), ".config", "opencode", "opencode.jsonc")
  );
}

/** Quote a YAML scalar so banyan's strict parser sees it verbatim. */
function yamlScalar(value: string): string {
  return value === "" ? '""' : JSON.stringify(value);
}

interface BanyanProfile {
  id: string;
  label: string;
  provider?: string;
  icon?: string;
  command: string;
}

export interface AgentListEntry {
  name: string;
  label: string;
  command: string;
  aliases: string[];
}

/**
 * Launchable registry entries in registry order. With `tag`, only entries
 * carrying that tag are returned (e.g. `workit agents --tag review`).
 */
export function listAgents(resolved: ResolvedConfig, tag?: string): AgentListEntry[] {
  const registryAgents = resolved.config.codingAgents?.agents ?? {};
  const entries: AgentListEntry[] = [];
  for (const [name, entry] of Object.entries(registryAgents)) {
    if (!isEntry(entry)) continue;
    if (!entry.command?.trim()) continue;
    if (tag && !entry.tags?.includes(tag)) continue;
    entries.push({
      name,
      label: entry.label ?? name,
      command: entry.command,
      aliases: entry.aliases ?? [],
    });
  }
  return entries;
}

/** Entries that surface in banyan's model picker, in registry order. */
export function banyanProfiles(resolved: ResolvedConfig): BanyanProfile[] {
  const registryAgents = resolved.config.codingAgents?.agents ?? {};
  const profiles: BanyanProfile[] = [];
  for (const [name, entry] of Object.entries(registryAgents)) {
    if (!isEntry(entry)) continue;
    if (!entry.tags?.includes("banyan")) continue;
    if (entry.picker === false) continue;
    if (entry.command === undefined) continue;
    profiles.push({
      id: name,
      label: entry.label ?? name,
      ...(entry.provider !== undefined ? { provider: entry.provider } : {}),
      ...(entry.icon !== undefined ? { icon: resolveHomePath(entry.icon) } : {}),
      command: entry.banyanCommand ?? entry.command,
    });
  }
  return profiles;
}

/** Abbreviate $HOME to ~ for display in generated headers. */
function displayPath(file: string): string {
  const home = homedir();
  return file.startsWith(home) ? `~${file.slice(home.length)}` : file;
}

export function generateBanyanYaml(resolved: ResolvedConfig): string {
  const lines = [
    `# Generated by \`workit sync\` from ${displayPath(resolved.registryFile ?? AGENTS_FILE)} — do not edit.`,
    "# Edit the registry instead; this file is rewritten automatically.",
    "session_launches:",
  ];
  const profiles = banyanProfiles(resolved);
  if (profiles.length === 0) {
    return lines.join("\n") + "\n";
  }
  for (const profile of profiles) {
    lines.push(`  - id: ${yamlScalar(profile.id)}`);
    lines.push(`    label: ${yamlScalar(profile.label)}`);
    if (profile.provider !== undefined) lines.push(`    provider: ${yamlScalar(profile.provider)}`);
    if (profile.icon !== undefined) lines.push(`    icon: ${yamlScalar(profile.icon)}`);
    lines.push(`    command: ${yamlScalar(profile.command)}`);
  }
  return lines.join("\n") + "\n";
}

/** The full opencode.jsonc document: schema, passthrough settings, generated agent map. */
export function generateOpencodeJsonc(resolved: ResolvedConfig): string {
  const codingAgents = resolved.config.codingAgents ?? {};
  const doc: Record<string, unknown> = {
    $schema: OPENCODE_SCHEMA,
    ...(codingAgents.opencode ?? {}),
    agent: buildOpencodeAgents(codingAgents.agents ?? {}),
  };
  return JSON.stringify(doc, null, 2) + "\n";
}

function buildOpencodeAgents(registryAgents: Record<string, CodingAgentEntry>): Record<string, unknown> {
  const generated: Record<string, unknown> = {};
  for (const [name, entry] of Object.entries(registryAgents)) {
    if (!isEntry(entry) || !entry.opencode) continue;
    const key = entry.opencodeName ?? name;
    if (generated[key] !== undefined) {
      throw new Error(`Duplicate opencode agent '${key}' produced by registry entries`);
    }
    generated[key] = entry.opencode;
  }
  // Preserve registry order while keeping disabled built-ins (build/plan) stable.
  const ordered: Record<string, unknown> = {};
  for (const builtin of ["build", "plan"]) {
    if (generated[builtin] !== undefined) ordered[builtin] = generated[builtin];
  }
  for (const [key, value] of Object.entries(generated)) {
    if (ordered[key] === undefined) ordered[key] = value;
  }
  return ordered;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isEntry(value: unknown): value is CodingAgentEntry {
  return isRecord(value);
}

function writeDerived(path: string, contents: string, check: boolean): SyncTargetResult {
  const existing = existsSync(path) ? readFileSync(path, "utf8") : undefined;
  if (existing === contents) return { path, changed: false };
  if (check) return { path, changed: true };

  mkdirSync(dirname(path), { recursive: true });
  // Preserve the last human-authored version once, so repeated syncs never bury it.
  let backupPath: string | undefined;
  if (existing !== undefined && !existing.includes("Generated by `workit sync`")) {
    backupPath = `${path}.orig`;
    if (!existsSync(backupPath)) copyFileSync(path, backupPath);
  }
  writeFileSync(path, contents);
  return { path, changed: true, ...(backupPath ? { backupPath } : {}) };
}

/**
 * Regenerate banyan's model-picker config and opencode.jsonc from the shared
 * registry. Idempotent: files are only rewritten when their content differs.
 */
export function syncDerivedConfigs(
  resolved: ResolvedConfig,
  options: SyncOptions = {},
): SyncResult {
  if (!resolved.config.codingAgents?.agents) {
    throw new Error(
      "no coding-agent registry found (~/.agents/agents.yml); refusing to rewrite derived configs",
    );
  }

  const check = options.check ?? false;
  const targets: SyncTargetResult[] = [
    writeDerived(banyanConfigPath(options.homeDirectory), generateBanyanYaml(resolved), check),
    writeDerived(opencodeConfigPath(options.homeDirectory), generateOpencodeJsonc(resolved), check),
  ];
  return { targets, changed: targets.some((target) => target.changed) };
}
